#!/bin/sh

TMP_FILE=.app.yaml

export GCP_PROJECT_ID=${GCP_PROJECT_ID:-randomuser-giga}
export REACT_APP_API_URL="https://api-dot-${GCP_PROJECT_ID}.appspot.com/api"

yarn run build

gcloud app deploy $TMP_FILE

rm $TMP_FILE
